#!/bin/sh

case "$1" in
    start)
        [ -f /etc/nimbus-banner ] && cat /etc/nimbus-banner
        ;;
    stop)
        # Nothing to stop for a banner service
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        ;;
esac
