#!/bin/sh

case "$1" in
    start)
        echo "Nimbus: starting login service"
        exec /bin/login
        ;;
    stop)
        echo "Nimbus: stopping login service"
        killall login 2>/dev/null
        ;;
esac
