#!/bin/sh

case "$1" in
    start)
        echo "Nimbus: network service not implemented yet"
        ;;
    stop)
        echo "Nimbus: stopping network service (nothing to stop)"
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        ;;
esac
